<a href="https://colab.research.google.com/github/luxc1101/ML/blob/master/Deeplearning_Ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Online Curse script 
This script is based on the online curse Deeplerning.AI from Andrew Ng (coursera Deeplerning.AI)

## A Note on Python/Numpy Vectors

In [5]:
import numpy as np

a = np.random.randn(5) # 5 random gauss distribut number
a

array([-0.8993467 , -1.73749907,  1.29063312,  1.70090919,  0.61341639])

In [6]:
a.shape # niether row vector nor colume vector

(5,)

In [7]:
print(a.T)

[-0.8993467  -1.73749907  1.29063312  1.70090919  0.61341639]


In [8]:
print(np.dot(a,a.T))

8.762833093746323


In [10]:
a = np.random.randn(5,1) 
a

array([[ 1.04395191],
       [-0.04389284],
       [-0.735084  ],
       [-2.28718941],
       [-0.2053788 ]])

In [11]:
print(a.T)

[[ 1.04395191 -0.04389284 -0.735084   -2.28718941 -0.2053788 ]]


In [12]:
print(np.dot(a,a.T))

[[ 1.08983560e+00 -4.58220171e-02 -7.67392349e-01 -2.38771576e+00
  -2.14405587e-01]
 [-4.58220171e-02  1.92658164e-03  3.22649264e-02  1.00391245e-01
   9.01465920e-03]
 [-7.67392349e-01  3.22649264e-02  5.40348488e-01  1.68127634e+00
   1.50970667e-01]
 [-2.38771576e+00  1.00391245e-01  1.68127634e+00  5.23123538e+00
   4.69740207e-01]
 [-2.14405587e-01  9.01465920e-03  1.50970667e-01  4.69740207e-01
   4.21804499e-02]]
